@startuml Connect4game

skinparam classAttributeIconSize 0
title Connect 4 Game
class Connect4
class Logic
abstract class Controller
class StartController
class GameController
class PlayController
class ResumeController
class BoardView
class ResumeView
abstract class Menu
class PlayMenu


Connect4 *-- Logic
Logic o-- Controller
Controller <|-- StartController
Controller <|-- GameController
Controller <|-- ResumeController
Menu <|- PlayMenu

GameController *-- PlayController
GameController *-- BoardView
GameController *-- ResumeView
GameController --> PlayMenu
PlayController o-- PlayMenu

Turn o-- "2" Player


@enduml