@startuml Connect4game

skinparam classAttributeIconSize 0
title Connect 4 Game
class Connect4
class GameController
class Game
class Turn
class GameView
class StartView
class ResumeView
class BoardView
class TurnView implements TurnVisitor
class HumanPlayer implements Player
class BotPlayer implements Player
class Board
class Direction
class Token
class Color
interface Player
interface TurnVisitor

Turn o-- "2" Player

Connect4 *-- GameController
GameController *-- Game
GameController *-- Turn
GameController *-- GameView
GameController *-- TurnView
GameController *-- BoardView
GameView *-- Game
GameView *-- StartView
GameView *-- ResumeView
Game *-- Board
StartView o-- Game
ResumeView o-- Game
Token o-- Color
Board o-- Token
Board --> Direction

@enduml